### ISSUE TITLE
Build the Deep Neural Network in LandscapeNotebook.ipnyb

### ISSUE THREAD

**Issue by sfd9898** [google/patents-public-data#15]
Hello,

Getting the following error and have been unable to trouble shoot so far:  

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-73e6904371e8> in <module>
----> 1 import model
      2 import importlib
      3 importlib.reload(model)
      4 
      5 model = model.LandscapeModel(td, 'data', seed_name)

~/patents-public-data/models/landscaping/model.py in <module>
     19 from keras.models import Sequential, Model
     20 from keras.layers import Dense, Input, Embedding, BatchNormalization, ELU, Concatenate
---> 21 from keras.layers import LSTM, Conv1D, MaxPooling1D, Merge
     22 from keras.layers.merge import concatenate
     23 from keras.layers.core import Dropout

ImportError: cannot import name 'Merge'

Thanks!

**Comment by seinberg** [comment]
Hmm, looks like this was removed from Keras. It's actually not used, so if you're feeling brave you can delete the ",Merge" from the import and delete the entire "wire_model()" function and send it over as a pull request that I can approve. That should fix your issue. I can probably get to this at some point later this week or early next week otherwise.

**Comment by sfd9898** [comment]
Might take a try in the next couple days. A bit outside my expertise but I will let you know if I think I figure it out. Thanks!

**Comment by sfd9898** [comment]
Submitted the edits and the chunk ran without error.

**Comment by seinberg** [comment]
Good to hear. I just made the corresponding change in the master repo too. Thanks for finding the issue and confirming it now works.
