### ISSUE TITLE
Load Inference Data in LandscapeNotebook.ipnyb

### ISSUE THREAD

**Issue by sfd9898** [google/patents-public-data#16]
Hello, receiving the following error in when I try to run code immediately following "Load Inference Data."

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-40-8c1811f28d1b> in <module>
      2 
      3 subset_l1_pub_nums, l1_texts, padded_abstract_embeddings, refs_one_hot, cpc_one_hot = \
----> 4     expander.sample_for_inference(td, 0.2)

~/patents-public-data/models/landscaping/expansion.py in sample_for_inference(self, train_data_util, sample_frac)
    535                 pickle.dump(
    536                     (subset_l1_pub_nums, l1_texts, padded_abstract_embeddings, refs_one_hot, cpc_one_hot),
--> 537                     outfile)
    538         else:
    539             print('Loading inference data from filesystem at {}'.format(inference_data_path))

OverflowError: cannot serialize a bytes object larger than 4 GiB

I tried to add "protocol=4" to the pickle.dump (see[ here](https://stackoverflow.com/questions/29704139/pickle-in-python3-doesnt-work-for-large-data-saving)) but still receive the same error.

**Comment by seinberg** [comment]
Hi, this is a common problem and stems from some of the patents having a
crazily large amount of text in them. Reduce the size of the sample on
which you're running inference. E.g., instead of 20% (0.2), reduce it to
0.05 to start with and try ratcheting it up slowly.

**Comment by sfd9898** [comment]
Awesome, thanks!
