### ISSUE TITLE
Better understanding Google Patents Research Dataset

### ISSUE THREAD

**Issue by svjan5** [google/patents-public-data#33]
Google Patents Research dataset (on BigQuery) has a table called annotations which has useful information for research. The schema of the annotations table comprises of the following columns:

1. publication_number
2. ocid
3. preferred_name
4. domain
5. source
6. confidence
7. character_offset_start
8. character_offset_end
9. inchi
10. inchi_key
11. smiles
12. conf_bucket

Most of the fields are understandable through their names and values. However, I am having a hard time figuring out what does **character_offset_start** and **character_offset_end** mean here. Intuitively, it should refer to character offset in the original patent documents (column 1) but since patents are mostly pdfs it is not very clear how to make use of it. If anyone has any idea then please share.

Thanks in advance

**Comment by wetherbeei** [comment]
I sent this over email but here's the same reply if others have the same question:

No problem! Happy to help - the character_offset fields are the number of bytes from the start of the full text where the annotation is found. We get both PDF and machine-readable text from patent offices (like you see on Google Patents). The offsets won't match up exactly with the text for various reasons, but you can use the relative position and distance for other tasks such as co-occurrence within a window of characters.

**Comment by svjan5** [comment]
Thanks a lot, @wetherbeei for your prompt reply. I can understand that Google must be using its own text extractors for pdfs so extracting the same text for using offset directly will be difficult. Sure, we will try to work with relative distances in that case. 

Thanks again!
