### ISSUE TITLE
Possible inconsistency between model tokenizer and white-paper example of 'prothesis'.

### ISSUE THREAD

**Issue by pmcwhannel** [google/patents-public-data#35]
When tokenizing 'prothesis' I expect this to map to a single numerical token; however it is mapped to two and when compared to the original BERT tokenizer they do the same thing. To my understanding this tokenizer should tokenize 
'prothesis' into a single token as previously mentioned as this is stated as an example in the white paper accompanying this repo. Additionally, I don't see the work prothesis in the .txt vocabulary file provided through this repo. I am curious if there was a change between what is in this repo and the white paper or if this is something new an unexpected?
![Tokenizer_issue](https://user-images.githubusercontent.com/61853401/106063504-2289d880-60ad-11eb-9835-8e63f01dca1c.PNG)

Note: I should mention I am converting this TensorFlow implementation and supported files to PyTorch and using HuggingFace.

**Comment by wetherbeei** [comment]
The vocab exists for "prosthesis" on line 30579 of bert_for_patents_vocab_39k.txt - "prothesis" is simply misspelled.

**Comment by pmcwhannel** [comment]
Thank you for the timely response!
