### ISSUE TITLE
Unable to use the Patent-BERT

### ISSUE THREAD

**Issue by kr-prince** [google/patents-public-data#41]
This is more of a query rather than a bug. Not sure where to ask.
I want to use the BERT embeddings for some patents so I followed the standard Tensorflow tutorial to use BERT (classify_text_with_bert.ipynb). I downloaded and unzipped the saved model and got something like this, very similar to the BERT model structure in the tutorial:
```
Archive:  saved_model.zip
   creating: temp_dir/rawout/
   creating: temp_dir/rawout/variables/
  inflating: temp_dir/rawout/variables/variables.data-00000-of-00001  
  inflating: temp_dir/rawout/variables/variables.index  
  inflating: temp_dir/rawout/saved_model.pb  
   creating: temp_dir/rawout/assets.extra/
  inflating: temp_dir/rawout/assets.extra/vocab.txt
```

Then instead of below line in the tutorial:
`bert_model = hub.KerasLayer('https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/1')`
I passed :
`bert_model = hub.KerasLayer('/content/temp_dir/rawout')`
It threw this error:
```
ValueError: Importing a SavedModel with tf.saved_model.load requires a 'tags=' argument if there is more than one MetaGraph. Got 'tags=None', but there are 2 MetaGraphs in the SavedModel with tag sets [['serve'], ['serve', 'tpu']]. Pass a 'tags=' argument to load this SavedModel.
```

So I tried 
`bert_model = hub.KerasLayer('/content/temp_dir/rawout', tags=['serve'])`
Then I got this error:
`ValueError: Signature name has to be specified for non-callable saved models (if not legacy TF1 Hub format).`

Can someone please help what is the correct way to use this model locally??

**Comment by robert-srebrovic** [comment]
There is no keras metadata included in the model so "hub.KerasLayer" won't work. There are two options for loading the model:

1) model = tf.compat.v2.saved_model.load(export_dir='your/model/dir', tags=['serve'])

OR

2) model = hub.load('your/model/dir', tags=['serve'])

Then when calling the model you will have to specify the signature such as:

model.signatures['serving_default'](
      segment_ids=segment_ids,
      input_mask=input_mask,
      input_ids=input_ids,
      mlm_positions=mlm_positions,
)
