### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by toddrjones** [google/patents-public-data#57]
This is probably a really easy question, but how do I download the patent data? For example, https://console.cloud.google.com/bigquery?project=erudite-marker-539&page=table&t=inventor_raw&d=JEMS16&p=erudite-marker-539&redirect_from_classic=true&ws=!1m5!1m4!4m3!1serudite-marker-539!2sJEMS16!3sinventor_raw

I tried Export - Export to GCS. And then I get stuck.

**Comment by wetherbeei** [comment]
Export to GCS is the way to go if you want a CSV dump - is there an error message? You can try following this guide: https://cloud.google.com/bigquery/docs/exporting-data. You'll need to create a new Google Cloud Storage bucket first in a US region: https://cloud.google.com/storage/docs/creating-buckets

**Comment by toddrjones** [comment]
Thank you for the response. I have created a Google Cloud Storage bucket in a US region. When I go to export, I get this error: "Access Denied: Project erudite-marker-539: User does not have bigquery.jobs.create permission in project erudite-marker-539."

**Comment by wetherbeei** [comment]
Ah, at the top of the page (right of "Google Cloud Platform") there should be a dropdown menu - you need to select a project you own to use for running the query (different from the erudite-marker-539 project that stores the public dataset).

**Comment by toddrjones** [comment]
Ah, I tried that and it solved my problem - thank you!

**Comment by alekssadowski95** [comment]
@toddrjones  I think you can close this issue now.
