### ISSUE TITLE
The link to google bigdata blog does not work

### ISSUE THREAD

**Issue by mu-wang** [google/patents-public-data#7]
The link "https://cloud.google.com/blog/big-data/2018/07/measuring-patent-claim-breadth-using-google-patents-public-datasets" for "this post on the Google Cloud Big Data Blog" leads to 404.

![image](https://user-images.githubusercontent.com/18296158/42327151-194a3bfe-8039-11e8-8275-809e853d2c18.png)
![image](https://user-images.githubusercontent.com/18296158/42327282-5b594922-8039-11e8-8bdf-e48d864b42d8.png)

**Comment by ostegm** [comment]
Thanks for the comment. The post will go live early next week.
